### PR TITLE
Create matplotlib sample using Db2 data and show various plot attributes

### PR DESCRIPTION
**Pull request by eric-simpson**

### CODE REVIEW

**Comment by ThePrez** [comment]
Trying to run the sample without X11 hooked up didn't quite work: 
```fortran
Traceback (most recent call last):
  File "matplotwithdb2data.py", line 30, in <module>
    plt.subplot(2,1,1)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1083, in subplot
    fig = gcf()
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/matplotlib/pyplot.py", line 525, in figure
    **kwargs)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1008, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/QOpenSys/pkgs/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

```
Is this expected?

**Comment by jwoehr** [comment]
> Trying to run the sample without X11 hooked up didn't quite work:
...
> _tkinter.TclError: no display name and no $DISPLAY environment variable
> ```
> 
> Is this expected?

If it has tkinter exposure, it won't run without X or, alternatively, some kind of headless setup.

**Comment by ThePrez** [comment]
> If it has tkinter exposure, it won't run without X or, alternatively, some kind of headless setup.

That's what's a little surprising, since the application doesn't explicitly use tkinter. It looks to be implicitly used by matplotlib (which shouldn't be _too_ surprising). 

Anyway, running with an X11 environment activated does produce a nice spiffy image file written to the filesystem

image

But the program proceeds to crash (from what looks to be a bad branch from PASE X11 libs). That's a bit confounding because writing the `.png` is the last thing the Python code tries to do. It might be some X11 exit processing going awry (?).

**Comment by jwoehr** [comment]
Works for me now without core dump

**Pull request merged**
