### PR TITLE
PHP Example

### PR DESCRIPTION
**Pull request by jbh**
More to come, but I wanted to get this out here at least.

### CODE REVIEW

**Comment by ThePrez** [comment]
A couple questions/comments about the handling of passwords:
- Doesn't `db2_connect()` allow passwordless login? 
- Rather than having the password in the source code, can we require an environment variable or a `.env` (is that standard in the PHP space?)

**Comment by jwoehr** [comment]
There's also the pattern of storing a `.ini` file somewhere else in the file system and use 
```
$my_ini = parse_ini_file('/some/file/path');
$uid = $my_ini['my_uid'];
$passwd = $my_ini['my_passwd'];
```
... etc.

**Comment by jbh** [comment]
What I have done is the community standard. Using an INI is an outdated methodology.

If you want to use blanks, then just configure with blanks. The configuration file is there for convenience, to allow one to configure the connection however they like.

This configuration is interoperable as well.

**Comment by jbh** [comment]
What I've done is basically the same as what frameworks do, sans the abstraction: https://docs.laminas.dev/laminas-db/adapter/#creating-an-adapter-using-configuration

**Review by kadler — APPROVED** [review]
LGTM, though I don't especially like seeing my crappy old jquery example carried on.

**Comment by jbh** [comment]
> LGTM, though I don't especially like seeing my crappy old jquery example carried on.

Well, I had to start somewhere. 🤣

**Comment by kadler** [comment]
I agree with @jbh. Lots of languages / frameworks use small code files for configuration: Ruby on Rails, Django, etc.

**Comment by kadler** [comment]
Hey @jbh looks like your git info is just AUTHORNAME/AUTHOREMAIL. Is that intentional?

**Comment by jbh** [comment]
That's really strange. It got overridden somehow. Thanks for the heads up.

**Comment by jbh** [comment]
I'm not sure why it's still complaining about DCO. I followed the instructions and added it to all my commits.

**Comment by kadler** [comment]
If you want to squash your changes and reset the author/commiter info (along with adding the sign-off) and force push it I'll merge things.

**Comment by jbh** [comment]
I got it finally. :D

**Comment by jbh** [comment]
What's holding this back? The commits have been amended with signature.

**Pull request merged**
